baseURL = "http://example.org/"
languageCode = "en-us"
title = "SV am Annette"
theme = "sv-theme"
copyright = "Copyright © 2022 Annette-Softwareentwicklung"
[menu]
  [[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Arbeitsgruppen"
    url = "/arbeitsgruppe/"
    weight = 3
  [[menu.main]]
    name = "Credits"
    url = "/credits/"
    weight = 4 # * weight gibt an, in welcher Reihenfolge "range" über diese iteriert
